name: Learning GitActions

on:
    push:
        branches:
            - learning

jobs:
    publishing:
    
        runs-on: ubuntu-latest

        steps:
            - name: Checkout to branch
              uses: actions/checkout@v4

            - name: Publish Image
              uses: mr-smithers-excellent/docker-build-push@v6
              with:
                image: deenath/prison-break-api
                registry: docker.io
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}